---
spring:
  application:
    name: weather
  output:
    ansi:
      enabled: detect
  profiles:
    active: local
#server:
  #context-path: /
  #port: 8080
management:
  context-path: /manage
  security:
    roles: oa--support-
#logging:
  #level:
    #org.springframework.security: DEBUG
kroger:
  eaf:
    version: 4.5.0
---
spring:
  profiles: local
---
spring:
  profiles: unittest
---
spring:
  profiles: cloud
